### ISSUE TITLE
question about rerank method

### ISSUE THREAD

**Issue by c-dada** [pse-ecn/expanded-cross-neighborhood#3]
Hi, I test rerank method on mars dataset,the performance can be improved,while on other video datasets the result is bad(such as DukeMTMC_VideoReID).Could you explain this?
Best wishes to you！
Thank you so much!

**Comment by ssarfraz** [comment]
I have seen some of the similar observations, i think current ECN_rankdist produce suboptimal results in the open-set eval scenario, since it basically set similarities of the samples to zero which are far away (this can be fixed easily by retaining the orig-dist values on these samples after the rerank). I will update the the ECN scripts to fix it soonish, when I have some time. Will let you know here.

**Comment by ssarfraz** [comment]
Hello @c-dada , sory for forgetting about it. I have updated both matlab and python ECN fns with fixes. Please update your local copies.
